CREATE DATABASE person;
CREATE DATABASE property;
CREATE DATABASE quiz;
CREATE DATABASE event;
CREATE DATABASE tournament;

GRANT ALL PRIVILEGES ON DATABASE person TO postgres;
GRANT ALL PRIVILEGES ON DATABASE property TO postgres;
GRANT ALL PRIVILEGES ON DATABASE quiz TO postgres;
GRANT ALL PRIVILEGES ON DATABASE event TO postgres;
GRANT ALL PRIVILEGES ON DATABASE tournament TO postgres;
