version: '2'

services:
  db:
    image: 'postgres:latest'
    container_name: psql-ms
    ports:
      - "5432:5432"
    networks:
      - none
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo

  backend:
    image: 'backend:latest'
    container_name: backend-c
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - none
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://ll:5432/demo

  react:
    image: 'react:latest'
    container_name: react-c
    build:
      context: ./frontend
    ports:
      - "9000:3000"
    networks:
      - none
    environment:
      - PORT=3000


networks:
  auctions:
    driver: bridge