server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
     ddl-auto: create-drop
     #  ddl-auto: update

