// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

package com.quizhub.systemevents.event;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
