spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          username: ${CONFIG_REPO_USERNAME}
          password: ${CONFIG_REPO_PASSWORD}
          default-label: main
server:
  port: 8888
